// URL base da API
@apiurl = http://127.0.0.1:8080
@auth-token = 5d85c56a909b6b4b

### Uma rota que não existe - devolverá 404 
GET {{apiurl}}/test HTTP/1.1

### Uma rota de teste - GET
GET {{apiurl}}/hello HTTP/1.1

### Uma rota de teste - GET
GET {{apiurl}}/helloget/Nuno HTTP/1.1
Authorization : {{auth-token}}

###
POST {{apiurl}}/hellopost HTTP/1.1
Authorization : {{auth-token}}
Content-Type: application/json

{ 
    "name": "ze"
}

###
POST {{apiurl}}/user/login HTTP/1.1
Content-Type: application/json

{ 
    "username": "gil",
    "password": "gil"
}

### 
GET {{apiurl}}/testebd HTTP/1.1
Authorization : {{auth-token}}

### 
OPTIONS {{apiurl}}/testebd HTTP/1.1
Authorization : {{auth-token}}